# Generated by Django 2.2.4 on 2019-08-17 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
            ],
            options={
                'verbose_name': '注文の商品',
                'verbose_name_plural': '注文の商品',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='注文番号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='オーダー番号')),
                ('pay_status', models.CharField(choices=[('success', '成功'), ('TRADE_CLOSED', '時間オーバー'), ('WAIT_BUYER_PAY', 'クリエイトオーダー'), ('cancel', 'キャンセル'), ('cancel', '支払い待ち')], default='paying', max_length=30, verbose_name='注文状態')),
                ('post_script', models.CharField(max_length=200, verbose_name='注文コメント')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='注文金額')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支払い時間')),
                ('address', models.CharField(default='', max_length=100, verbose_name='届出先')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='受取人')),
                ('singer_mobile', models.CharField(max_length=20, verbose_name='連絡先')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='購入数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'ショッピングカート',
                'verbose_name_plural': 'ショッピングカート',
            },
        ),
    ]
